name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What are you trying to achieve? What workaround do you use today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Willingness to contribute
      options:
        - label: I am willing to submit a pull request for this feature
